language: node_js
node_js:
 - "6"
sudo: required
env:
  - NODE_ENV='test'
before_script:
  - npm install --save-dev jest-react-native
  - npm install --save-dev babel-preset-react-native 
  - npm install --save react-native-code-push
  - react-native link react-native-code-push
script:
  - npm test
notifications:
  email: false
