language: node_js
node_js:
 - "6"
sudo: required
env:
  - NODE_ENV='test'
before_script:
  - npm install --save-dev jest-react-native
  - npm install --save-dev babel-preset-react-native 
script:
  - npm test
notifications:
  email: false
