language: node_js
node_js:
 - "6"
sudo: required
env:
  - NODE_ENV='test'
script:
  - npm install -g react-native-cli
  - npm install --save-dev jest-react-native 
  - npm test
notifications:
  email: false
